swent-sp-2024-event-radar/event-radar-app

- README.md
> Add Figma links to README

- app/google-services.json
**Objective**
Create the Google Firebase Datastore to store "users" and "events" information and connect it to the app project. 
**Key Changes:**
- Updated the `google-services.json` file.
Related to Issue #14
> Connected Firebase Datastore to Project

- app/src/main/java/com/github/se/eventradar/ui/theme/Color.kt
- app/src/main/java/com/github/se/eventradar/ui/theme/Theme.kt
Add the figma material design to Colors.kt and Theme.kt, according to this : https://www.figma.com/file/yO8KgaCa6F39yUdyPSfkpn/Material-3-Design-Kit-(Community)?type=design&node-id=49823-12142&mode=design&t=QQREwP4DR1RFVCmz-0
> Added color and material from figma mockup

- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
- app/src/main/java/com/github/se/eventradar/ui/login/LoginScreen.kt
- app/src/main/java/com/github/se/eventradar/ui/login/SignUpScreen.kt
- app/src/main/java/com/github/se/eventradar/ui/navigation/NavGraph.kt
- app/src/main/java/com/github/se/eventradar/ui/navigation/NavigationActions.kt
Redirected the successful Log In and Sign Up to the Homepage rather than the Overview
> Homepage Integration

- README.md
Updated README.md file with user database structure via JSON tree.
> Updated README.md file with user database structure

- app/src/main/java/com/github/se/eventradar/model/EventsOverviewViewModel.kt
A quick fix to EventsOverviewViewModel. This is solely to get the app up and running fixing a bad PR from the last sprint. Deleted incorrectly formatted event documents in Firebase as well.
> Quick event null fix

- README.md
Create a section in the README that outlines the structure of the firebase database for messages.
closes #92
> Add messages database structure to README

- app/src/main/java/com/github/se/eventradar/model/EventsOverviewViewModel.kt
- app/src/main/java/com/github/se/eventradar/model/event/EventList.kt
- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
- app/src/test/java/com/github/se/eventradar/EventOverviewViewModelTest.kt
-  Reinstated the previously implemented getEvents and getUpcomingEvents methods(from #131) in EventsOverviewViewModel, which were removed in a prior merge. The ViewModel utilizes the revised repository interfaces. 
- Added tests for EventOverviewViewModel
- Updated home for DI
- Fixed typo in EventList
> Event overview view model final version

- app/build.gradle.kts
- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
Small changes to fix the EventOverviewViewModel Bug
> Fixed Cannot Create Instance Of EventOverviewViewModel Bug

- app/src/main/java/com/github/se/eventradar/ui/login/SignUpScreen.kt
Bug:
- Cannot type a "/" in the DOB field due to numeric keyboard
Main change:
- Removed numeric keyboard from DOB field
Closes #189
> Bug Fix: Cannot type "/" in DOB sign up field

- app/src/main/java/com/github/se/eventradar/model/repository/user/FirebaseUserRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/user/IUserRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/user/MockUserRepository.kt
- app/src/test/java/com/github/se/eventradar/MockUserRepositoryUnitTest.kt
Related issue #193 => Closes #193 
- Created a Map implementation of MockImageDatabase in MockUserRepository
- Created corresponding getImage and uploadImage functions
- Tested these functions in MockUserRepositoryTests.kt > 80% Line Coverage
> MockUserRepository Tests & Mock Get/Upload Image functions

- scrum/SCRUM Board - Backlog.tsv
Main change:
- Added tsv file of SCRUM board for Sprints 4-6 to the repo
> Updated SCRUM board for Sprints 4-6

- .gitignore
- app/.gitignore
- app/build.gradle.kts
- app/src/androidTest/java/com/github/se/eventradar/qrCode/qrCodeScanFriendUiTest.kt
- app/src/androidTest/java/com/github/se/eventradar/screens/qrCodeScanFriendUiScreen.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/se/eventradar/ui/navigation/NavGraph.kt
- app/src/main/java/com/github/se/eventradar/ui/qrCode/QrCodeFriendUi.kt
- app/src/main/java/com/github/se/eventradar/ui/qrCode/QrCodeScanner.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/qrCode/QrCodeAnalyser.kt
- build.gradle.kts
Trying to get Joyti's changes back in a second small PR
> QrCodeRecovery

- app/src/androidTest/java/com/github/se/eventradar/messages/MessagesTest.kt
- app/src/main/java/com/github/se/eventradar/ui/messages/Messages.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/MessagesViewModel.kt
- app/src/test/java/com/github/se/eventradar/MessagesViewModelTest.kt
- create the View Model for the Contacts list screen
- augment the messages view model with a `getFriends()` function that returns a list of type `User` which corresponds to the user objects for each friend
- use the new `getCurrentUserId()` function implemented in #183 
- add tests
closes #200
> Add friends list view model and add tests

- app/src/main/java/com/github/se/eventradar/ui/component/ReusableComponents.kt
- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
- app/src/main/res/values/strings_event.xml
- refactor the Search Bar component of `SearchBarAndFilter` to be used in other components
> Make Search Bar a Separate Reuasble Component

- app/src/androidTest/java/com/github/se/eventradar/messages/EmptyMessagesTest.kt
- app/src/androidTest/java/com/github/se/eventradar/messages/MessagesTest.kt
- app/src/androidTest/java/com/github/se/eventradar/screens/MessagesScreen.kt
- app/src/main/java/com/github/se/eventradar/ui/component/ReusableComponents.kt
- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
- app/src/main/java/com/github/se/eventradar/ui/messages/Messages.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/MessagesViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/github/se/eventradar/MessagesViewModelTest.kt
- implement UI that accompanies VM implemented in #200 
- implement UI for Friends List
- edit and add UI tests
https://github.com/swent-sp-2024-event-radar/event-radar-app/assets/64320145/625c5dc3-67a0-478a-8eed-b43001be90bc
Closes #201
> Implement Friends List UI

- app/src/main/java/com/github/se/eventradar/model/event/Event.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/ChatViewModel.kt
- app/src/test/java/com/github/se/eventradar/ChatViewModelUnitTest.kt
- Added "bio" field that was missing in some tests and files.
- Changed toMap function from `ticket_quantity` to `ticket_capacity` instead.
- Browse events fixed.
> Bug Fix for Browse Events

- app/src/main/java/com/github/se/eventradar/viewmodel/EventDetailsViewModel.kt
- app/src/test/java/com/github/se/eventradar/EventDetailsViewmodelUnitTest.kt
- Implement VM for Cancel Registration user flow
> Add registration cancellation method in Event VM

- app/src/main/java/com/github/se/eventradar/model/repository/event/FirebaseEventRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/event/MockEventRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/message/FirebaseMessageRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/message/IMessageRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/message/MockMessageRepository.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/ChatViewModel.kt
- app/src/test/java/com/github/se/eventradar/ChatViewModelUnitTest.kt
- app/src/test/java/com/github/se/eventradar/FirebaseMessageRepositoryUnitTest.kt
- app/src/test/java/com/github/se/eventradar/MockMessageRepositoryUnitTest.kt
- Implemented `observeMessages(user1: String, user2: String)` in both Mock and Firebase message repositories to enable real-time updates in chat interactions.
-  Developed a private `observeMessages()` function within `ChatViewModel` to encapsulate the logic for observing chat messages. This function is called in the init block.
- Wrote comprehensive tests for all functions to ensure they handle both success and failure scenarios effectively.
- Conducted a live application testing to validate the functionality and real-time performance of the messaging feature.
> Implemented real-time updates for private chats

- app/src/androidTest/java/com/github/se/eventradar/MockDatabaseModules.kt
- app/src/main/java/com/github/se/eventradar/model/di/LocationModule.kt
- app/src/main/java/com/github/se/eventradar/model/repository/location/ILocationRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/location/MockLocationRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/location/NominatimLocationRepository.kt
- app/src/test/java/com/github/se/eventradar/MockLocationRepositoryUnitTest.kt
- app/src/test/java/com/github/se/eventradar/NominatimLocationRepositoryUnitTest.kt
- Created a NominatimLocationRepository and MockLocationRepository to simplify ViewModel testing for createEvent (and later on edit event).
Reasoning behind this is because fetching the location is a function that uses an external service (uses OkHttp3 to send request to Nominatim OpenStreetMap to fetch longtitude, latitude and name of file), therefore putting it in a Repository helps separate the external dependencies from ViewModel/UI.
- Created the Repository Files.
- Created tests for these files.
Related to #309 + #76  => Closes #309
> Location Repository + Tests

- app/src/androidTest/java/com/github/se/eventradar/hosting/HostingTest.kt
- app/src/androidTest/java/com/github/se/eventradar/screens/HostingScreen.kt
- app/src/main/java/com/github/se/eventradar/ui/component/ReusableComponents.kt
- app/src/main/java/com/github/se/eventradar/ui/hosting/Hosting.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/EventsOverviewViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/HostedEventsViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/SearchFilterUiState.kt
- app/src/main/res/values/strings_event.xml
- app/src/test/java/com/github/se/eventradar/HostedEventsViewModelTest.kt
Main changes:
- added UI + VM for search and filter in my hostings page
To be completed:
- Convert "my hostings" page to scaffold > constraint layout
> My Hostings - search & filter

- app/src/main/java/com/github/se/eventradar/ui/home/Home.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/AuthenticationViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/CreateEventViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/EventsOverviewViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/HostedEventsViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/MessagesViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/ViewFriendsProfileViewModel.kt
Chnaged to state.update in all VMs!
> Ensuring more atomicity 

- app/src/main/java/com/github/se/eventradar/ui/hosting/Hosting.kt
Fixed bug related to "create event" and "map/list" button floating at top of screen when search is active.
> Bug fix - FABs on "My Hostings" page

- README.md
Document properly our app functionalities and code packages
Following coaches advice, here is some more documentation about what the app does, what features it contains, as well with some quick description of the main packages used in the code.
Feedback from MS3
> [Ungraded]
> (not graded) [Too little] Very few comments on some intricate parts of the code
> (not graded) [None] There are no detailed descriptions provided for the packages. It could be beneficial to include brief descriptions of the main packages to explain the rationale behind the design choices made during their creation
> (not graded) [Partial] You might want to add a few pieces of information to your project-level readme such as: description of the app / features, testing, running the app
This was ungraded in MS3 but it …
> Packages and features documentation in the readme

- app/build.gradle.kts
- app/src/androidTest/java/com/github/se/eventradar/screens/ProfileScreen.kt
- app/src/androidTest/java/com/github/se/eventradar/viewProfile/ProfileTest.kt
- app/src/main/java/com/github/se/eventradar/model/repository/user/FirebaseUserRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/user/IUserRepository.kt
- app/src/main/java/com/github/se/eventradar/model/repository/user/MockUserRepository.kt
- app/src/main/java/com/github/se/eventradar/ui/viewProfile/ProfileUi.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/AuthenticationViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/ProfileViewModel.kt
- app/src/main/java/com/github/se/eventradar/viewmodel/user/UserViewModelHelperFunctions.kt
- app/src/main/res/drawable/edit.xml
- app/src/test/java/com/github/se/eventradar/ProfileViewModelUnitTest.kt
Implementation of the Edit Profile Screen. It has been merged into the profile screen and activated upon clicking the edit icon. 
- Upon clicking the edit icon the UI displays outlined text fields instead of texts
- A save button is present at the bottom of the screen to update the user info in the database
- Left to implement: Log out button and delete account button
> Edit profile vm+UI

- app/src/main/java/com/github/se/eventradar/ui/qrCode/QrCodeTicketUi.kt
delete event title from scan QR
> final PR ever

- README.md
> Demo to readme
